name        : bc
version     : 1.06
release     : 4
source      :
    - http://ftp.gnu.org/gnu/bc/bc-1.06.tar.gz : 4ef6d9f17c3c0d92d8798e35666175ecd3d8efac4009d6457b5c99cea72c0e33
homepage    : http://www.gnu.org/software/bc/bc.html
license     :
    - GPL-2.0
summary     : The GNU bc arbitrary precision calculator language
replaces    :
    - dc
description : |
    GNU bc is an interactive algebraic language with arbitrary precision which follows the POSIX 1003.2 draft standard, with several extensions including multi-character variable names, an `else' statement and full Boolean expressions
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
