name        : bc
version     : 1.06.95
release     : 5
source     :
    - http://alpha.gnu.org/gnu/bc/bc-1.06.95.tar.bz2 : 7ee4abbcfac03d8a6e1a8a3440558a3d239d6b858585063e745c760957725ecc
license     :
    - GPL-2.0
summary     : The GNU bc arbitrary precision calculator language
replaces    :
    - dc
description : |
    GNU bc is an interactive algebraic language with arbitrary precision which follows the POSIX 1003.2 draft standard, with several extensions including multi-character variable names, an `else' statement and full Boolean expressions
setup      : |
    %patch -p1 < $pkgfiles/bc_l.patch
    %configure
build      : |
    %make
install    : |
    %make_install
